plugins {
    id 'com.android.application'
    id 'kotlin-android'
}
android {
    namespace 'com.qaisqk543.qistbook'
    compileSdk 34
    defaultConfig {
        applicationId 'com.qaisqk543.qistbook'
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName '1.0.0'
    }
    signingConfigs {
        release {
            storeFile file(project.rootDir.absolutePath + '/app/keystore.jks')
            storePassword System.getenv('KEYSTORE_PASSWORD') ?: 'Katz@7kptke6h!'
            keyAlias 'appkey'
            keyPassword System.getenv('KEY_PASSWORD') ?: 'Katz@7kptke6h!'
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions { jvmTarget = '17' }
    packagingOptions {
        resources { excludes += ['/META-INF/{AL2.0,LGPL2.1}'] }
    }
}
dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.webkit:webkit:1.12.1'
    implementation 'androidx.core:core-ktx:1.13.1'
    implementation 'androidx.activity:activity-ktx:1.9.0'
}